version: "2"
services:
  grav:
    image: thespad/grav:develop
    container_name: grav
    restart: unless-stopped
    environment: 
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/adam/dev/test/grav/config:/config
    networks:
      - proxy
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.grav-all.rule=Host(`grav.spad.uk`)
      - traefik.http.routers.grav-all.entrypoints=https,http
      - traefik.http.routers.grav-all.service=grav-svc
      - traefik.http.routers.grav-all.middlewares=middleware-https-redirect
      - traefik.http.services.grav-svc.loadbalancer.server.port=80

networks:
  proxy:
    external: true